### ISSUE TITLE
Different states tax calculation

### ISSUE THREAD

**Issue by Definence** [taxjar/taxjar-ruby#69] opened 2021-05-06 10:25 UTC
Hello there. I am trying to calculate tax for order where sender and a recipient are in different states. For some reason it returns zero. If sender and recipient are in the same state it works as expected. Can you explain this?

Params
`{:amount=>5000,
 :shipping=>1006,
 :line_items=>[{:retail_price=>5000, :discounted_price=>nil, :variant_id=>"3", :quantity=>1, :product_tax_code=>"20010", :unit_price=>5000, :retailer_id=>2, :weight=>1.0, :discount=>0}],
 :from_zip=>"94025",
 :from_state=>"CA",
 :from_city=>"Menlo Park",
 :from_street=>"2825 Sand Hill Rd",
 :from_country=>"US",
 :retailer_id=>2,
 :to_zip=>85297,
 :to_state=>"AZ",
 :to_city=>"Gilbert",
 :to_street=>"3301 Greenfield Rd",
 :to_country=>"US"}`

Response
`<Taxjar::Tax order_total_amount: 6006.0, shipping: 1006.0, taxable_amount: 0.0, amount_to_collect: 0.0, rate: 0.0, has_nexus: false, freight_taxable: false, tax_source: nil, exemption_type: nil>`

**Comment by Char5180** [comment] 2021-08-04 15:11
> Hello there. I am trying to calculate tax for order where sender and a recipient are in different states. For some reason it returns zero. If sender and recipient are in the same state it works as expected. Can you explain this?
> 
> Params
> `{:amount=>5000, :shipping=>1006, :line_items=>[{:retail_price=>5000, :discounted_price=>nil, :variant_id=>"3", :quantity=>1, :product_tax_code=>"20010", :unit_price=>5000, :retailer_id=>2, :weight=>1.0, :discount=>0}], :from_zip=>"94025", :from_state=>"CA", :from_city=>"Menlo Park", :from_street=>"2825 Sand Hill Rd", :from_country=>"US", :retailer_id=>2, :to_zip=>85297, :to_state=>"AZ", :to_city=>"Gilbert", :to_street=>"3301 Greenfield Rd", :to_country=>"US"}`
> 
> Response
> `<Taxjar::Tax order_total_amount: 6006.0, shipping: 1006.0, taxable_amount: 0.0, amount_to_collect: 0.0, rate: 0.0, has_nexus: false, freight_taxable: false, tax_source: nil, exemption_type: trust>`

**Comment by Char5180** [comment] 2021-08-04 15:11
@Definence

**Comment by Char5180** [comment] 2021-08-04 15:12
> 
Duplicate of #70

**Comment by Char5180** [comment] 2021-08-04 15:13
I'm sorry for not being a little more at home why I heard that scooter it was great and I love you more than anything

**Comment by poops** [comment] 2022-08-12 21:01
This doesn't seem to be an issue with the plugin. If you're still having an issue, please reach out to the support team https://www.taxjar.com/contact. Thanks!

**Closed by poops** 2022-08-12 21:01 UTC
