### ISSUE TITLE
Support for ruby 2.7

### ISSUE THREAD

**Issue by milboj** [taxjar/taxjar-ruby#57] opened 2020-04-01 18:20 UTC
Do you support ruby 2.7? I tried to use this gem in 2.7 environment and I get error **FrozenError (can't modify frozen String: "")**

I assume that this error is related with recent changes in ruby core https://rubyreferences.github.io/rubychanges/2.7.html#core-methods-returning-frozen-strings

I didn't find any usage of this in your code but maybe some dependency is making problem.

**Comment by ScottRudiger** [comment] 2020-04-02 02:52
Thanks for the issue and the [corresponding PR](https://github.com/taxjar/taxjar-ruby/pull/58) @milboj!

Could you share what method you were calling when this error occurred? Or provide some code that reproduces the issue?

I tried testing on Ruby v2.7.0 and v2.7.1 so far without hitting the error.

**Comment by milboj** [comment] 2020-04-02 10:01
Method tax_for_order makes me a problems, but I didn't test others. I analyzed TaxJar code and in your code I didn't find anything that could be problematic, but I figure one dependency could be. You set in gemspec file allowed versions for the "http" gem are 'http', '>= 1.0', '< 5.0'. Versions before 4.3 doesn't have support for ruby 2.7 and in my Gemfile.lock was loaded older version. When I updated that "http" gem, I didn't find any problem.  

Try to set older version of http < 4.3 before you make tests on Ruby 2.7.

**Comment by prsimp** [comment] 2020-04-02 13:55
@ScottRudiger -- looks like the `http` gem dropped support for Ruby 2.0 and 2.1 in the [3.0 release](https://github.com/httprb/http/blob/4-x-stable/CHANGES.md#300-2017-10-01) and dropped support for 2.2 in the [4.0 release](https://github.com/httprb/http/blob/4-x-stable/CHANGES.md#300-2017-10-01).

I know we've dropped support for Ruby versions < 2.0 but seems like we need to decide whether we want to support 2.0-2.2 (`http < 3.0`) or 2.7 (`http >= 4.3`) cc: @fastdivision

**Comment by ScottRudiger** [comment] 2020-04-02 17:06
Thanks @milboj & @prsimp, I was able to verify the issue. Agreed we need to decide on what versions to support. Perhaps it would make sense to support Ruby 2.3+ with `http >= 4.3`.

**Comment by ScottRudiger** [comment] 2020-04-02 22:53
> Perhaps it would make sense to support Ruby 2.3+ with `http >= 4.3`.

OK, spoke to @fastdivision and we'll go with this. 👍

**Comment by ScottRudiger** [comment] 2020-04-06 15:46
Resolved in #58.

**Closed by ScottRudiger** 2020-04-06 15:46 UTC
